### ISSUE TITLE
Can't add integration

### ISSUE THREAD

**Issue by joni347** [dave-code-ruiz/uponorX265#1]
Hi @dave-code-ruiz,
I have downloaded the integration but when I try to add it I get the following error:

The configuration flow could not be loaded: {"message":"Invalid handler specified"}

**Comment by thecem** [comment]
@dave-code-ruiz This solve the issue, installation of a complete new HA installation going with two reasons wrong:

First:
The configuration flow could not be loaded: {"message":"Invalid handler specified"}  -> const.py DOMAIN = "uponor" // DOMAIN = "uponorX265" make sure this in the last version since after downloading the integration it is : `DOMAIN = "uponor"`

Second:
https://github.com/dave-code-ruiz/uponorX265/pulls should solve the issue.

And big kudos for you, to switch to your repo! THANKS A LOT!

**Comment by nisarerbest** [comment]
Hi. Awesome work. I'm getting the exact same error when trying to install. Since I need the previous fix, I didn't uninstall aserv version, but just disabled it

**Comment by dave-code-ruiz** [comment]
please @nisarerbest @thecem @joni347 can you test it now?

**Comment by nisarerbest** [comment]
Same issue still. I redownloaded, as Instill see the 4d old release 1.0

**Comment by joni347** [comment]
I've just tried it too. Can confirm @nisarerbest

**Comment by thecem** [comment]
@dave-code-ruiz may you have to release a new release with the master.

**Comment by dave-code-ruiz** [comment]
Ok thanks @thecem 

I release versión 1.0.1

Try again

**Comment by joni347** [comment]
Get the following error when I try to update:
Downloading dave-code-ruiz/uponorX265 with version 1.0.1 failed with (No manifest.json file found 'custom_components/uponorX265/manifest.json')

**Comment by dave-code-ruiz** [comment]
ok, i need you delete folder config/custom_components/uponorX265 or rename uponorX265 to uponorx265

Another option is go to HACS -> Uponor Smatrix X-265 module R-208 repository -> three dots -> delete and when finish, download again

Thnks you for your help

**Comment by joni347** [comment]
That's what I did. I think the problem is that the manifest.json still says "version": "1.0.0".

**Comment by dave-code-ruiz** [comment]
Not it is a problem version in manifiest.json is not used

Please review folder config/custom_components/uponorX265 the X caracter i need it is lowcase

Thanks

**Comment by joni347** [comment]
I have deleted everything that has to do with the installation. Now I can't even download the integration anymore. When I try to download it via hacs, I just get the error message 
Downloading dave-code-ruiz/uponorX265 with version 1.0.1 failed with (No content to download)

Übersetzt mit DeepL https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation

**Comment by joni347** [comment]
@thecem, @nisarerbest I have another question that has nothing to do with this topic. Are you connected to the Uponor cloud and which firmware version is running on your controller (X265)?

**Comment by nisarerbest** [comment]
I have 3 controllers connected to Uponor cloud. They all say V1.21. My R-208 unit says version 20002123. I hope this is what you're looking for

**Comment by joni347** [comment]
@nisarerbest yes that was what I'm looking for. Did you update to the latest firmware provided by uponor?

**Comment by dave-code-ruiz** [comment]
> I have deleted everything that has to do with the installation. Now I can't even download the integration anymore. When I try to download it via hacs, I just get the error message Downloading dave-code-ruiz/uponorX265 with version 1.0.1 failed with (No content to download)
> 
> Edit: I had to restart HA. Now it's working
> 
> Edit2: I was able to add the integration and it is running. Thank you very much for your support!

Great news , 

i will try to add this repo to HACS soon

Thnks

**Comment by nisarerbest** [comment]
I switched over to this from asev. It is working flawlessly! Thank you so much! ❤️

**Comment by joni347** [comment]
@nisarerbest do you have controller software update enabled in the Uponor app?

**Comment by nisarerbest** [comment]
> @nisarerbest do you have controller software update enabled in the Uponor app? 

Yes, but I've never seen an update

**Comment by joni347** [comment]
> > [@nisarerbest](https://github.com/nisarerbest) do you have controller software update enabled in the Uponor app?
> 
> Yes, but I've never seen an update

Thank you very much! I have version 1.16 on my controller and was always afraid to update because I was afraid that the HomeAssistant interface would not work anymore.
